-- Create profiles table to extend auth.users
create table profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null default 'customer' check (role in ('admin', 'customer')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles enable row level security;

-- Create audit_logs table
create table audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users on delete set null,
  action text not null,
  details jsonb
);

alter table audit_logs enable row level security;

-- Add new columns to products
alter table products 
add column if not exists available_sizes text[],
add column if not exists available_flavors text[];

-- Drop insecure policies from initial schema
drop policy if exists "Enable insert for anon users" on products;
drop policy if exists "Enable update for anon users" on products;
drop policy if exists "Enable delete for anon users" on products;

drop policy if exists "Enable insert for anon users" on store_settings;
drop policy if exists "Enable update for anon users" on store_settings;

-- Create Helper function to check if user is admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Policies for Profiles
create policy "Users can read their own profile" on profiles
  for select using (auth.uid() = id);

create policy "Admins can read all profiles" on profiles
  for select using (public.is_admin());

-- Policies for Products (Read is already enabled for all)
create policy "Admins can insert products" on products
  for insert with check (public.is_admin());

create policy "Admins can update products" on products
  for update using (public.is_admin());

create policy "Admins can delete products" on products
  for delete using (public.is_admin());

-- Policies for Store Settings (Read is already enabled for all)
create policy "Admins can insert store_settings" on store_settings
  for insert with check (public.is_admin());

create policy "Admins can update store_settings" on store_settings
  for update using (public.is_admin());

-- Policies for Audit Logs
create policy "Admins can read audit logs" on audit_logs
  for select using (public.is_admin());

create policy "Admins can insert audit logs" on audit_logs
  for insert with check (public.is_admin() or auth.uid() = user_id);
