-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  image_url text,
  category text,
  stock_status text default 'in_stock' check (stock_status in ('in_stock', 'limited', 'out_of_stock'))
);

-- Create store_settings table
create table store_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_open boolean default false,
  closing_message text
);

-- Insert default store settings
insert into store_settings (id, is_open, closing_message)
values (1, false, 'We are currently closed.');

-- Enable Row Level Security (RLS)
alter table products enable row level security;
alter table store_settings enable row level security;

-- Create policies (Allow public read, allow anon insert/update/delete for demo purposes)
-- In a real app, you'd restrict write access to authenticated users only.

create policy "Enable read access for all users" on products for select using (true);
create policy "Enable insert for anon users" on products for insert with check (true);
create policy "Enable update for anon users" on products for update using (true);
create policy "Enable delete for anon users" on products for delete using (true);

create policy "Enable read access for all users" on store_settings for select using (true);
create policy "Enable insert for anon users" on store_settings for insert with check (true);
create policy "Enable update for anon users" on store_settings for update using (true);
