-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text not null,
  status text not null default 'pending' check (status in ('pending', 'completed', 'cancelled')),
  total_amount numeric not null default 0
);

-- Enable RLS
alter table orders enable row level security;

-- Policies
create policy "Admins can select orders" on orders
  for select using (public.is_admin());

create policy "Admins can insert orders" on orders
  for insert with check (public.is_admin());

create policy "Admins can update orders" on orders
  for update using (public.is_admin());
